### ISSUE TITLE
Reload data when it's updated. Do not restart the server when source code is updated.

### ISSUE THREAD

**Issue by lukipuki** [lukipuki/COVID-19-simulation#25]
We wanted to react to data updates, so we run the Flask server like so:
```
server.run(host="0.0.0.0", port=8081, debug=True, extra_files=data_dir.glob("*.data"))
```

However, this restarts the server even when code is updated, which is not what we want.

**Comment by lukipuki** [comment]
https://github.com/lukipuki/COVID-19-simulation/pull/30 doesn't update the data, just restarts the server :grinning:

**Comment by lukipuki** [comment]
Also, the server is restarted even on non-mutating events such as opening a file. We need to filter those out.

**Comment by lukipuki** [comment]
I think I fixed the data reload issue in https://github.com/lukipuki/COVID-19-simulation/pull/31 via the introduction of `_run_flask_server`, but restarting on file open is still happening.

**Comment by Aj0SK** [comment]
Ok, inotify has terrible documentation but i figured out that we can rewrite this as follows:
`mask = inotify.constants.IN_MODIFY`
`i = inotify.adapters.InotifyTree(str(data_dir), mask = mask)` as there is parameter mask that I couldn't find anywhere on their website. But this reacts to created files in ../data for example

**Comment by lukipuki** [comment]
Created files are good. I'll try this out and perhaps add it to my PR (to speed the fix up)

**Comment by lukipuki** [comment]
I've added the mask into https://github.com/lukipuki/COVID-19-simulation/pull/31 and it works (on my localhost ™).

**Comment by Aj0SK** [comment]
I tried to load new server before killing the other one but there seems to be some internal problem that server starts but it's not working.

**Comment by lukipuki** [comment]
Mine works just fine. Is there some error message?
