### ISSUE TITLE
Do not run Flask as a production server

### ISSUE THREAD

**Issue by lukipuki** [lukipuki/COVID-19-simulation#58]
Flask's been trying to tell us something for a few weeks:
```
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
```

I don't like running yet another app infront of nginx, so FastCGI seems to be the way to go: https://flask.palletsprojects.com/en/1.1.x/deploying/fastcgi/

**Comment by rejdi** [comment]
I would say, this is the right task for Nginx in front of python backend and later for static file serving.
