### ISSUE TITLE
Create UI for automatized predictions

### ISSUE THREAD

**Issue by lukipuki** [lukipuki/COVID-19-simulation#61]

**Comment by miskosz** [comment]
I have created #71 which is the most straightforward way to display the predictions - for a country, display all predictions in one graph. I have left a comment there, I think we should merge only if we see this as a temporary state an it will not break the server :)

**Comment by miskosz** [comment]
Regarding labels, what did you mean?

![80426579-4df55200-88e6-11ea-9203-df40df700841](https://user-images.githubusercontent.com/2885431/80536014-9faae480-8999-11ea-905a-acd6890a2e52.png)

Specifying t0 is tricky.

**Option 1**
I don't really like TeX in the label, but I sense that this might sound controversial. I would prefer if the labels were

- Bodova & Kollar Mar 29
- Bodova & Kollar Apr 12
- Daily prediction Apr 28

and then put the specific values for A, Tg, exp and T0 under the graph.

**Option 2**
With TeX, but values only:
- Mar 29: a=2, tg=3, exp=4, t0=may 10
- Apr 12: ...
- Apr 28*: ...

**Option 3**
Some version of what we have now.

**Comment by lukipuki** [comment]
The big argument against TeX is that it's really slow to render. Also, it gets messy when there're so many numbers shown.

Regarding option three:

- Bodova & Kollar Mar 29 (α=6.23)
- Bodova & Kollar Mar 29 (α=6.23, TG=7.2)

(Or something similar, only give a glimpse of the real parameters and then list all of them below or above. For example the parameter A is not interesting, t0 probably too. )

**Comment by rejdi** [comment]
TeX - both problems can be fixed.
Slowness: we may pre-render formulas as HTML or as Images
Mess: there is no need to show those formulas always. We may show them on request (hover, some click, ...). Another approach is to move the legend under or beside graph.

**Comment by lukipuki** [comment]
@rejdi we shouldn't clutter it with too many formulas. When I plot many predictions, the only parameters I look at are α and TG. The exact formula can be written elsewhere. But I agree that if we can show it e.g. on mouse hover, that would be great (though that sucks on mobile).

**Comment by lukipuki** [comment]
We also want a UI with a slider - the slider picks a date of the automatic prediction. Should we have a separate issue for it? It seems like this one is aimed more for showing more predictions in one graph, while the slider would allow picking just one from a certain date.

**Comment by rejdi** [comment]
@lukipuki No slider yet.

**Comment by miskosz** [comment]
Let's ship a version with fixed predictions first and make the slider another issue.

**Comment by lukipuki** [comment]
What remains to be done here?
