### ISSUE TITLE
Make AtgModelFit easier to use

### ISSUE THREAD

**Issue by lukipuki** [lukipuki/COVID-19-simulation#88]
We need to use `AtgModelFit` at many places but it's hard to use. Examples:

- To serialize an instance of `AtgModelFit` we need to actually access the trace generator via the `FittedFormula` class. This should be much simpler, we should just call `AtgModelFit.serialize` or similar. Right now there are 3 classes involved.
```python
        trace_generator = formula.get_trace_generator(country_report)
        parameters.alpha = formula.fit.exp
        parameters.tg = formula.fit.tg
        parameters.offset = formula.fit.t0
        parameters.a = formula.fit.a
        parameters.start_date.year = trace_generator.start_date.year
        parameters.start_date.month = trace_generator.start_date.month
        parameters.start_date.day = trace_generator.start_date.day
```
- To make the usage of `AtgModelFit.predict` easier, I've added `def shift_forward(self, day_count: int) -> None: self.t0 -= day_count`, but that's not a very good style.

I think we should fix the class by doing the following
-  AtgModelFit needs to store (`start_date` and `offset`) or (`date_zero` and `t0`). I'm voting for the former: no one cares about `date_zero`, but `start_date` is useful.
- We can add a `predict_date(date)` function, which calculates `x=date - start_date` and then calls `predict(x)`. This is useful for users that want to work with dates instead of numbers. I'd keep `predict()` as it is now: `x=0` is at `start_date`.

@miro-balaz might have opinions too

**Comment by miro-balaz** [comment]
I would sugest having sci-kit like model(.fit, .predict methods) called AtgModel at the bottom, that would accept only numeric vectors, and will know nothing about metadatadata (date_until, start_date, country_name) ,but we have to add get_draw_interval() method. This is basically turning atg_model.py into class And then there would be class that handles all data transformations called for now ModelWrapper, which would be composed with AtgModel. ModelWrapper will call .fit method of the AtgModel in its fit method . This is basically separating FittedFormula.get_trace_generator into .fit and .get_trace_generator which would use fit fitted in .fit. Then convenience functions could be added.

**Comment by lukipuki** [comment]
Some more observations:

- Our automated predictions need to end up in the prediction database. The database is made out of `CountryPrediction` class, which references a `Formula`. In this case, it will be `FittedFormula` which stores `AtgModelFit` as `self.fit`. So accessing the fit is possible via `CountryPrediction.formula.fit`.

- `FittedFormula` right now stores `start_date` indirectly inside `self.trace_generator`, but this should be more readily available. E.g. we should be able to do `CountryPrediction.formula.start_date` (or similar).

- `FittedFormula` should be constructible from explicitly provided `α`, `tg` and the other parameters. This is useful for deserialization and other purposes.

I think `FittedFormula` is fine as Miro's suggested `ModelWrapper`. We just need to refactor it a bit.

**Comment by lukipuki** [comment]
After https://github.com/lukipuki/COVID-19-simulation/pull/91 I'm quite satisfied with `FittedFormula`, which encapsulates `AtgModelFit` as `FittedFormula.fit`.
