### ISSUE TITLE
Add daily predictions to prediction_db

### ISSUE THREAD

**Issue by rejdi** [lukipuki/COVID-19-simulation#94]
So the web infrastructure may easily use daily predictions.

**Comment by lukipuki** [comment]
Code for parsing the proto and keeping only the "reasonable predictions" is at https://github.com/lukipuki/COVID-19-simulation/blob/53c906d1864ab7a521f4909d05e4700f7345162c/covid_graphs/covid_graphs/country_graph.py#L344-L355

We should support the same functionality in the prediction database. The code above from `country_graph.py` should be (mostly) removed.

**Comment by lukipuki** [comment]
In `country_dashboard.py` we select the -1th and -8th prediction days, we should have an API call for this too:
https://github.com/lukipuki/COVID-19-simulation/blob/bb2247505eaf865a29d7ac0786dfbb6311a1e53a/python/covid_web/covid_web/country_dashboard.py#L203

Alternatively just return all predictions and the user will pick the right dates.
